repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^backend/
        
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        files: ^backend/
        
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'cd backend && source .venv/bin/activate && PYTHONPATH=. pytest tests/'
        language: system
        pass_filenames: false
        always_run: true
        files: ^backend/.*\.py$